- name: Cambiar hostname según IP
  hosts: all
  become: yes
  vars:
    ip_hostname_map:
      "10.66.86.5":  STO-101
      "10.66.86.6":  STO-102
      "10.66.86.7":  STO-103
      "10.66.86.8":  STO-104
      "10.66.86.9":  STO-105
      "10.66.86.10": STO-106
      "10.66.86.11": STO-107
      "10.66.86.12": STO-108
      "10.66.86.13": STO-109
      "10.66.86.14": STO-110
      "10.66.86.15": STO-111
      "10.66.86.16": STO-112
      "10.66.86.22": STO-118
      "10.66.86.23": STO-119
      "10.66.86.24": STO-120
      "10.66.86.25": STO-121
      "10.66.86.26": STO-122
      "10.66.86.27": STO-123
      "10.66.86.28": STO-124
      "10.66.86.29": STO-125
      "10.66.86.48": STO-126
      "10.66.86.31": STO-201
      "10.66.86.32": STO-202
      "10.66.86.33": STO-203
      "10.66.86.34": STO-204
      "10.66.86.35": STO-205
      "10.66.86.36": STO-206
      "10.66.86.37": STO-207
      "10.66.86.38": STO-208
      "10.66.86.39": STO-209
      "10.66.86.40": STO-210
      "10.66.86.41": STO-211
      "10.66.86.42": STO-212
      "10.66.86.45": STO-301
      "10.66.86.46": STO-302
      "10.66.86.47": STO-303
      "10.66.86.57": STO-304
      "10.66.86.49": STO-305
      "10.66.86.50": STO-306
      "10.66.86.51": STO-307
      "10.66.86.52": STO-308
      "10.66.86.53": STO-309
      "10.66.86.54": STO-310
      "10.66.86.55": STO-311
      "10.66.86.56": STO-312

  tasks:

    - name: Obtener la IP del cliente
      command: hostname -I
      register: ip_output

    - name: Extraer la IP principal
      set_fact:
        ip_actual: "{{ ip_output.stdout.split()[0] }}"

    - name: Obtener el hostname correspondiente
      set_fact:
        nuevo_hostname: "{{ ip_hostname_map[ip_actual] }}"
      when: ip_actual in ip_hostname_map

    - name: Cambiar el hostname si corresponde
      hostname:
        name: "{{ nuevo_hostname }}"
      when: nuevo_hostname is defined

    - name: Confirmar cambio de hostname
      debug:
        msg: "Hostname cambiado a {{ nuevo_hostname }}"
      when: nuevo_hostname is defined
